- name: Build FE
  when: fe_app_repo is defined
  remote_user: "{{ deployer_user.name }}"
  command: chdir={{ fe_app_path }}
    bash -lc '{{ fe_build_command }}'

- name: Restart server
  remote_user: "{{ deployer_user.name }}"
  command: bash -lc "pm2 startOrRestart ecosystem.config.js --env production"
  args:
    chdir: "{{fe_app_path}}"
